server:
  port: ${PORT:8088}

spring:
  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_CHAT_MODEL:llama3}
      embedding:
        model: ${OLLAMA_EMBEDDING_MODEL:all-minilm}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: ${PREFER_IP_ADDRESS:true}
    hostname: ${RENDER_SERVICE_NAME:localhost}
